CREATE DATABASE IF NOT EXISTS tax_system;

USE tax_system;

CREATE TABLE IF NOT EXISTS users (

    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    username VARCHAR(100) UNIQUE NOT NULL,

    email VARCHAR(150) UNIQUE NOT NULL,

    password VARCHAR(255) NOT NULL

);

CREATE TABLE IF NOT EXISTS tax_history (

    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    username VARCHAR(100) NOT NULL,

    income DOUBLE NOT NULL,

    old_tax DOUBLE NOT NULL,

    new_tax DOUBLE NOT NULL,

    recommendation VARCHAR(500),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);